hvsock: Fix accept4() warnings
Non-standard Linux extension accept4() required _GNU_SOURCE to be defined.
If not, following warnings are expected:
    hvsock_linux.go: In function ‘accept_hv’:
    hvsock_linux.go:33:12: warning: implicit declaration of function ‘accept4’

If flags is 0 then accept4() is the same as accept(), so in this case let's
use accept() and get rid of warnings.

Signed-off-by: Vladislav Grishenko <themiron@mail.ru>